---
fontsize: 10pt
geometry: margin=0.5in
output:
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r, include=F}
source("0_Header.R") # Load Header

### Put any temporary functions here (to be put into function files later)
```

---
title: "`r ProjectName` Deidentify Files"
author: "`r AuthorName`, `r AuthorAffiliation`"
date: "`r format(Sys.time(),format="%B %d, %Y")`"
---

\newpage

=======================================

# Information 

In this file, we filter data by creating a keep col.

## Load the data
```{r}
# by csv or Rdata
# df <- read.csv(paste0(deidentified_data_folder,"file.csv"), stringsAsFactors=FALSE)

# load("Support/Rdata/RELMS_201516_cleaned_dfs.Rdata")
```

## Tag the data

For now, we are not deleting anything- simply flagging which data should be deleted.

```{r limitCond,echo={{rmd_data}},message={{rmd_data}}, cache={{rmd_cache}}, warning={{rmd_data}}}

w$keep <- T # Default we keep unless otherwise noted
```

## Filter the data


## Write intermediate files
```{r}
# write.csv(df,paste0(identified_data_folder,"/df_filtered.csv"),row.names=F)
# save(list=c("df"), file = "Support/Rdata/df_filtered.Rdata")

```
